version: "3"
services:
    node-app:
      container_name: my-express-app
      build: .
      volumes:
        - ./src:/app/src:ro
      ports:
        - "4000:4000"
      env_file:
        ./src/.env
      environment:
        - Node_Env:"development"
      depends_on:
        - mongo-app
    mongo-app:
      image: mongo
      restart: always
      volumes:
        - mongo-db/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME:root
        - MONGO_INITDB_ROOT_PASSWORD:example
volumes:
  mongo-db:
